
import './globals.css'; 
import ClientLayout from './ClientLayout'; 
 
export const metadata = { 
  title: 'My App', 
  description: 'Generated by Next.js', 
}; 
 
export default function RootLayout({ children }) {

  return ( 
    <html lang="en"> 
      <body> 
        <ClientLayout> 
          {children} 
        </ClientLayout> 
      </body> 
    </html> 
  ); 
} 
